name: Info-ZIP build
on: [push]
jobs:
  build-zip-win-x64:
    runs-on: windows-latest
    steps:
      - name: check out repository code
        # odd that this doesn't happen by default
        uses: actions/checkout@v4
      - name: set up VC++ build environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: build zip
        run: "cd zip\\win32 ; nmake -f makefile.w32"
      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: zip-win-x64
          path:
            zip/win32/zip.exe
